export const DESCRIPTION_SHORT =
  "Viata este ca un Univers frumos in care ne dorim sa fim fericiti, iubiti, sanatosi si in care sa ne bucuram de mult noroc. De multe ori ne intrebam ce trebuie sa facem pentru ca viata sa ramana acelasi Univers frumos, visat. De aceea eu, Tamaduitoarea si Clarvazatoarea Sunita, am descoperit calea prin care pot sa va implinesc aceste dorinte ajutata fiind de un dar mostenit, darul magiei albe, prin care pot adduce binele in casele si vietile voastre.";

export const DESCRIPTION_LONG =
  "Fie ca aveti problem in dragoste, in sanatate, in relatiile cu prietenii sau cu colegii, fie ca aveti problem la serviciu sau cu banii, eu, Tamaduitoarea si Clarvazatoarea Sunita pot sa aduc linistea si rezolvarea acestora.Am devenit cunoscuta de oamenii de pretutindeni prin puterea cuvantului transmis de catre cei carora le-am indeplinit visele. Am vindecat oameni, am reunit familii care s-au destramat si am adus dragostea in viata oamenilor iar puterea mea nu s-a oprit aici. Pot sa scot argintul viu, sa citesc viitorul cu cartile de tarot sis a ii ajut pe cei bogati cat sip e cei saraci in aceeasi masura, pot sa indepartez farmecele sis a dezleg bluestemele avand acea putere divina mostenita diin strabuni: Am devenit cunoscuta de oamenii de pretutindeni prin puterea cuvantului transmis de catre cei carora le-am indeplinit visele. Am vindecat oameni, am reunit familii care s-au destramat si am adus dragostea in viata oamenilor iar puterea mea nu s-a oprit aici. Pot sa scot argintul viu, sa citesc viitorul cu cartile de tarot sis a ii ajut pe cei bogati cat sip e cei saraci in aceeasi masura, pot sa indepartez farmecele sis a dezleg bluestemele avand acea putere divina mostenita diin strabuni, PUTEREA MAGIEI ALBE…Eu, Sunita, cea mai mare Tamaduitoare si Calrvazatoare din Romania, cunoscuta si recunoscuta oriunde in lume, aduc fericirea in viata dumneavoastra!";

export const LABEL_TEXT_MID =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies vitae nibh id tincidunt. Cras consequat lacinia ante eu cursus. Morbi in felis vel quam maximus feugiat. Aenean dui erat, dictum vitae semper nec, gravida at sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer venenatis commodo commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris interdum sodales mauris, in cursus ex vestibulum non. Duis ornare rhoncus venenatis. Ut eget augue luctus, aliquet eros eu, aliquet tortor. Curabitur justo lectus, feugiat at rhoncus eu, elementum at velit. ";

export const LABEL_TEXT_LONG =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies vitae nibh id tincidunt. Cras consequat lacinia ante eu cursus. Morbi in felis vel quam maximus feugiat. Aenean dui erat, dictum vitae semper nec, gravida at sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer venenatis commodo commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris interdum sodales mauris, in cursus ex vestibulum non. Duis ornare rhoncus venenatis. Ut eget augue luctus, aliquet eros eu, aliquet tortor. Curabitur justo lectus, feugiat at rhoncus eu, elementum at velit. Phasellus a ipsum ornare, porttitor nibh ullamcorper, placerat felis. Proin dapibus iaculis sem, vel interdum sapien venenatis eget. Pellentesque congue nec justo vel lobortis. Sed vehicula lorem turpis, sed fringilla urna porttitor eu. Nam sed urna id lorem dignissim pulvinar at eu libero. Phasellus nec eros sit amet leo blandit auctor. Vivamus erat sapien, tincidunt eget efficitur vel, euismod et ipsum. Ut rhoncus, mi in vulputate sagittis, nulla leo rhoncus massa, at pellentesque odio massa et nisi. Nunc lobortis venenatis sodales. Aenean consectetur tincidunt dui vitae sodales. Nullam tristique ultrices euismod. Donec sodales luctus ante sed placerat. Phasellus non eros ullamcorper, vulputate ligula non, aliquam leo. Aliquam at tempus neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum augue ut lorem dapibus accumsan. Vestibulum accumsan ullamcorper metus, in tincidunt urna. Curabitur volutpat, ligula non facilisis ultrices, tortor erat egestas urna, ultricies laoreet augue nulla eu quam. Etiam faucibus vitae massa eget euismod. Etiam porttitor leo eget est vestibulum laoreet. Integer massa magna, finibus ac luctus sed, facilisis sed nunc. Sed consequat facilisis diam, ut rhoncus lacus rhoncus in. Curabitur eleifend aliquet ante a aliquam. Sed pellentesque nisl eu urna pharetra accumsan. Nulla at libero a elit vestibulum porttitor. Aliquam mauris turpis, fringilla ut purus at, imperdiet suscipit velit. Nunc pretium ac lorem at consequat. ";

export const INTRO_TEXT =
  "Celebra cunoscuta prezicatoare si tamaduitoare, unica in Romania, cu cele mai multe cazuri rezolvate, este faimoasa Sunita, singura cu acest nume autentic, fiica Reginei Maria Campina. Are cele mai eficiente leacuri si ritualuri pentru rezolvarea problemelor dvs.";

export const MIDDLE_TEXT =
  "Daca simtiti ca sunteti BLESTEMATI, sau NU VA MERGE BINE, NU va gasiti ROSTUL IN VIATA, banuiti ca aveti FARMECE, BLESTEME, aveti PROBLEME IN DRAGOSTE, v-a PARASIT IUBITUL SAU IUBITA, aveti CERTURI IN CASNICIE, NU VA MERGE BINE IN AFACERI SAU SANATATE, SUFERITI DE BOLI SAU VICII, APELATI CU MAXIMA INCREDERE!";

export const CLARVIZIUNEA_TEXT =
  "Clarviziunea este abilitatea de a vedea cu puterea mintii, o putere care ma ajuta de fiecare data sa intampin raul si astfel sa gasesc calea de al indeparta doar prin puterea binelui.Pentru un clarvazator, un om este o poveste pe care o exprima prin fiecare element ce-l reprezinta din trecut si prezent. Numai descoperind aceste elemente pot sa gasesc drumul spre un viitor cladit pe sperante implinite.Am fost mediatizata pe posturi tv, ziare, reviste autorizate in Romania si astfel am aratat tuturor ca pot vedea trecutul, prezentul si viitorul, dezlega cele mai puternice farmece, vraji, blesteme, ca pot impreuna personae despartite, va pot ajuta s ava casatoriti, sa aveti norocul iubirii, s ava bucurati de spor si reusite in afaceri.Prin citirea trecutului am descoperit oamenii si astfel, am vindecat impotenta, alcoolismul, frica prin cele mai puternice ritualuri ce dainuie de sute de ani.De-a lungul timpului am inteles ca detin o putere rezultata din Credinta, Credinta ca Dumnezeu ne da Puterea sa credem in binecuvantare si adevar.";

export const TAROTUL_TEXT =
  "Tarotul este practica veche utilizata in prezicerea viitorului sau identificarea prezentului. Arata interpretarii cartilor de tarot nu este destinata oricui. Exista un dar divin pe care l-am mostenit si prin care eu pot interpreta simbolistica acestora.Tarotul ne spune ce optiuni avem, ce posibilitati se leaaga de aceste optiuni. Prin cartile de tarot poti raspunde la unele inrebari, poti adduce la suprafata raspunsuri ce exista in adancul finite tale fara sa iasa la iveala.Cartile de tarot ne raspund unor intrebari exacte de aceea trebuie sa stim ce ne dorim sa aflam astfel incat sa putem primi si raspunsul.Eu am puterea de a interpreta simbolurile, explicatia fiind una reala: nimic nu este intamplator asa cum si cartile alese de noi sunt alese pentru a ne identifica, a ne arata calea pe care ne drim sa o urmam.";

export const ASTROLOGIA_TEXT =
  "Astrologia inglobeaza un ansamblu de cunostinte, traditii si credinte, tructurate din punct de vedere geographic in sisteme care acorda importanta si semnificatie raporturilor ce se nasc din pozitiile relative ale corpurilor ceresti.Oamenii de stiinta, de-a lungul timpului, au demonstrate ca miscarile si pozitiile corpurilor ceresti influenteaza direct viata pe Pamant sau corespund unor evenimente din viata umana, evenimentelor trecute si prezente precum si la prezicerea viitorului.Tamaduitoarea si Clarvazatoarea Sunita pune la dispozitie mai multe servicii de astrologie precum: Horoscop de dragosteHoroscop pentru carieraHoroscop de sanatateInterpretarea astrogrameiNumerologieChiromantia  Se spune ca fiecare persoana se naste cu un destin iar viata este o calatorie. Nu trebuie sa fi om de stiinta ca sa-ti dai seama ca unele lucruri nu pot fi explicate insa nu poti ignora anumite semen divine.De-a lungul timpului oamenii au incercat sa-si ghiceasca viitorul iar pentru acest lucru au apelat la diferite practice";

export const CHIROMANTIA_TEXT =
  "Chiromantia sau gicitul in palma este una din cele mai vechi metode de divinatie din lume insa practicarea ei nu a fost niciodata atestata istoric. Daca forma mainnii si a degetelor poate sa ne dea atatea amanunte interesante, cu atat mai multe lucruri aflam daca studiem liniile ce brazdeaza palmna unei persoane.Liniile sunt brazdele, mai mult sau putin adanci, mai mult sau putin lungi, care strabat mana in toate directiile. Liniile sunt mai bine inseminate pe mana stanga, de aceea in chiromantie se studiaza intai aceasta mana.In studiul chiromantiei fiecare linie are insemnatatea ei dupa forma pe care o are si dupa pozitia fata de celelalte linii, in special de liniile principale.";
